iteration: 10000
display_interval: 10
progressbar_interval: 100
snapshot_interval: 1000
evaluation_interval: 100

gan_type: BIGGAN  # SNGAN or BIGGAN
batchsize:
  BIGGAN: 5  # batchsize per gpu (only multiple gpu training is supported)
  SNGAN: 25
image_sizes:
  BIGGAN: 256
  SNGAN: 128
snapshot:
  BIGGAN: 'biggan.npz'
  SNGAN: 'sngan.npz'

n_classes: 1000 # number of classes in pre-trained generator

initialize: True
not_initial_gamma: False
not_initial_beta: False
random: False
data_path: "data directory path"
dataset: "flowers"  # face, flower, flower_77, FFHQ, Anime
save_path: "results/"

train: False
finetune: False
datasize: 32
initial_z: "zero" # "zero" or "random"
l_emd: 0.1  # lambda for earth mover distance of z
l_re: 0.02  # lambda for gamma and beta
l_patch_dis: 0.0
l_gp: 0.0
l_per: 0.001 # if negative adaptive learning rate, else use l_per
perceptual_type: l1
normalize_l1_loss: False
loss_type: nsgan
perceptual: True  # use perceptual loss
tmp_for_test: 0.3
normalize_stat: False

lr_g_linear: 0.0000001 # lr for linear
exponential_shift_interval: 3000
init_lr: 0.03
